name: "Build tests on platforms"

on:
  workflow_dispatch:
  push:
    branches:
    - master
  pull_request:

permissions:
  id-token: write

jobs:
  build-linux:
    name: Build Linux
    strategy:
      matrix:
        include:
        - config: generic.docker
          system: x86_64-linux
          builds: [ toplevel, release ]
        - config: generic.docker
          system: aarch64-linux
          builds: [ toplevel, release ]
        - config: installer
          system: x86_64-linux
          builds: [ toplevel, release, vm ]
        - config: installer
          system: aarch64-linux
          builds: [ toplevel, release, vm ]
        - config: slate
          system: aarch64-linux
          builds: [ toplevel, release, vm ]
        - config: nova
          system: x86_64-linux
          builds: [ toplevel, vm ]
        - config: zenith
          system: x86_64-linux
          builds: [ toplevel, vm ]
        - config: fabric
          system: x86_64-linux
          builds: [ toplevel, release, vm ]
        - config: velvet
          system: x86_64-linux
          builds: [ toplevel, release, vm ]
        - config: lithos
          system: x86_64-linux
          builds: [ toplevel, release, vm ]
        - config: tecton
          system: x86_64-linux
          builds: [ toplevel, release, vm ]
        - config: tsrvbld
          system: x86_64-linux
          builds: [ toplevel, vm ]
        - config: thaum
          system: x86_64-linux
          builds: [ toplevel, vm ]
        - config: castor
          system: aarch64-linux
          builds: [ toplevel, release, vm ]
        - config: castor
          system: x86_64-linux
          builds: [ toplevel, release, vm ]
        - config: pollux
          system: aarch64-linux
          builds: [ toplevel, release, vm ]
        - config: pollux
          system: x86_64-linux
          builds: [ toplevel, release, vm ]
      fail-fast: false
    runs-on: ${{matrix.system == 'x86_64-linux' && 'ubuntu-24.04' || 'ubuntu-24.04-arm'}} 
    steps:
    - uses: actions/checkout@main
      with:
        ref: ${{github.ref}}
    - uses: NixOS/nix-installer-action@main
    - uses: Mic92/niks3-action@main
      with:
        server-url: https://niks3.usertam.dev
    - name: Build toplevel for ${{matrix.system}}.${{matrix.config}}
      if: contains(matrix.builds, 'toplevel')
      run: |
        nix build -L --keep-going \
          .#packages.${{matrix.system}}.nixosConfigurations.${{matrix.config}}.config.system.build.toplevel
    - name: Build vm for ${{matrix.system}}.${{matrix.config}}
      if: contains(matrix.builds, 'vm')
      run: |
        nix build -L --keep-going --option post-build-hook "" \
          .#packages.${{matrix.system}}.nixosConfigurations.${{matrix.config}}.config.system.build.vm
    - name: Build release for ${{matrix.system}}.${{matrix.config}}
      if: contains(matrix.builds, 'release')
      run: |
        nix build -L --keep-going --option post-build-hook "" \
          .#packages.${{matrix.system}}.nixosConfigurations.${{matrix.config}}.config.system.build.release
        find -L result -name '*.zst' -exec cp -a {} . \;
        echo "artifact=$(ls *.zst | tee /dev/stderr)" >> "$GITHUB_ENV"
    - uses: actions/upload-artifact@main
      if: env.artifact != ''
      with:
        name: ${{env.artifact}}
        path: ${{env.artifact}}

  build-darwin:
    name: Build Darwin
    strategy:
      matrix:
        config: [ gale, work ]
      fail-fast: false
    runs-on: macos-15
    steps:
    - uses: actions/checkout@main
      with:
        ref: ${{github.ref}}
    - uses: NixOS/nix-installer-action@main
    - uses: Mic92/niks3-action@main
      with:
        server-url: https://niks3.usertam.dev
    - name: Build ${{matrix.config}}.toplevel
      run: |
        nix build -L --keep-going .#darwinConfigurations.${{matrix.config}}.config.system.build.toplevel

  build-status:
    name: Build Status
    runs-on: ubuntu-latest
    needs: [build-linux, build-darwin]
    if: always()
    steps:
    - run: ${{!contains(needs.*.result, 'failure')}}
