name: "Stage flakes updates"
on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * MON'
permissions:
  contents: write
  pull-requests: write
jobs:
  staging:
    name: Stage updates on staging branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: DeterminateSystems/nix-installer-action@main
    - name: Set up github-actions name and email
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    - name: Update flake lock file
      run: |
        git switch -c staging
        nix flake update --commit-lock-file
        if ! git diff origin/master staging --exit-code; then
          echo "FLAKE_UPDATE=true" >> $GITHUB_ENV
        fi
    - name: Create pull request
      if: env.FLAKE_UPDATE == 'true'
      run: |
        git push -f origin staging:staging
        gh pr create --base master --head staging \
          --reviewer "@github-actions" \
          --body "Automatic update running `nix flake update --commit-lock-file`."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
